from __future__ import annotations

SECTION_ALIASES: dict[str, list[str]] = {
    "summary": [
        "summary",
        "professional summary",
        "profile",
        "about me",
        "career objective",
        "objective",
    ],
    "experience": [
        "experience",
        "work experience",
        "professional experience",
        "employment history",
        "work history",
    ],
    "education": ["education", "academic background", "academics"],
    "skills": ["skills", "technical skills", "core competencies", "expertise"],
    "projects": ["projects", "key projects", "personal projects"],
    "certifications": ["certifications", "licenses", "certificates"],
    "languages": ["languages", "language proficiency"],
    "achievements": ["achievements", "awards", "accomplishments"],
}

SKILL_TAXONOMY: dict[str, list[str]] = {
    "programming_languages": [
        "python",
        "java",
        "javascript",
        "typescript",
        "bash",
        "powershell",
        "c",
        "c++",
        "c#",
        "go",
        "rust",
        "ruby",
        "php",
        "scala",
        "kotlin",
        "swift",
        "r",
        "sql",
    ],
    "frameworks": [
        "django",
        "flask",
        "fastapi",
        ".net",
        "asp.net core",
        "rest api",
        "spring",
        "spring boot",
        "react",
        "angular",
        "vue",
        "next.js",
        "node.js",
        "express",
        "tensorflow",
        "pytorch",
    ],
    "cloud_platforms": [
        "aws",
        "azure",
        "gcp",
        "google cloud",
        "docker",
        "kubernetes",
        "terraform",
        "cloudformation",
        "eks",
        "aks",
        "k3s",
        "kind",
        "ec2",
        "lambda",
        "iam",
        "vpc",
        "s3",
        "rds",
        "app services",
        "key vault",
        "storage accounts",
        "azure sql",
        "entra id",
        "entraid",
        "bicep",
    ],
    "databases": [
        "postgresql",
        "postgres",
        "mysql",
        "mariadb",
        "sqlite",
        "mongodb",
        "redis",
        "elasticsearch",
        "cassandra",
        "dynamodb",
        "snowflake",
        "oracle",
        "ms sql server",
        "sql server",
        "azure sql",
    ],
    "data_and_ai": [
        "pandas",
        "numpy",
        "scikit-learn",
        "spark",
        "hadoop",
        "mlflow",
        "xgboost",
        "langchain",
        "openai",
        "llm",
        "nlp",
        "computer vision",
        "ai assistant",
        "azure sdk",
        "boto3",
    ],
    "devops_and_tools": [
        "git",
        "github",
        "github actions",
        "gitlab",
        "jenkins",
        "circleci",
        "azure devops",
        "gitops",
        "argocd",
        "helm",
        "kustomize",
        "kubectl",
        "yaml",
        "prometheus",
        "grafana",
        "loki",
        "datadog",
        "cloudwatch",
        "incident response",
        "slo",
        "sli",
        "sla",
        "devsecops",
        "jira",
        "confluence",
        "linux",
        "bash",
        "power bi",
        "tableau",
        "airflow",
    ],
    "soft_skills": [
        "communication",
        "leadership",
        "collaboration",
        "problem solving",
        "stakeholder management",
        "mentoring",
        "ownership",
        "time management",
    ],
    "domain_keywords": [
        "fintech",
        "healthcare",
        "ecommerce",
        "cybersecurity",
        "saas",
        "logistics",
        "banking",
        "telecom",
    ],
}

SKILL_CANONICAL_MAP: dict[str, str] = {
    "entraid": "entra id",
    "azure bicep": "bicep",
    "rest apis": "rest api",
    "rest api": "rest api",
    "apis": "api",
    "sql server": "ms sql server",
    "ms sql": "ms sql server",
    "postgres": "postgresql",
    "github action": "github actions",
    "git ops": "gitops",
    "app service": "app services",
    "azure app service": "app services",
    "azure app services": "app services",
    "keyvault": "key vault",
    "storage account": "storage accounts",
    "slo/sli/sla": "slo sli sla",
    "least privilege": "least-privilege",
}
